import { writeFile, access } from "node:fs/promises";
import { constants } from "node:fs";
import { resolve, join } from "node:path";
import { rules as staticRules } from "../checks/registry.js";

/** The config file `revivify init` scaffolds. */
export const CONFIG_FILENAME = ".revivify.yaml";

/** The default ship-ready bar: a perfect 10/10 (decision log #9). */
export const DEFAULT_THRESHOLD = 10;

/** The four Lighthouse category gates the full audit rolls up. */
export const LIGHTHOUSE_CATEGORIES = [
  "performance",
  "accessibility",
  "seo",
  "best-practices",
] as const;

export interface InitOptions {
  /** Overwrite an existing .revivify.yaml instead of leaving it untouched. */
  force: boolean;
}

/**
 * Compose the `.revivify.yaml` scaffold.
 *
 * The rule toggles are generated from the live check registry so the config
 * never drifts from the checks that actually run. Every check is on by default;
 * the human turns one off only as a deliberate, documented "your call".
 */
export function renderConfig(): string {
  const ruleLines = staticRules.map((rule) => `  ${rule.id}: true`).join("\n");
  const categoryLines = LIGHTHOUSE_CATEGORIES.map((id) => `  ${id}: true`).join("\n");

  return `# .revivify.yaml — how Revivify gates this project.
# Generated by \`revivify init\`. Safe to edit; re-run with --force to regenerate.
# Docs: https://github.com/jakewisnieski/revivify

# Ship-ready bar: the trust score (0–10) a page must reach to pass the gate.
# Default is a perfect 10 — every applicable check passing.
threshold: ${DEFAULT_THRESHOLD}

# Individual checks. Every check is on by default; set one to false only when
# you've made a deliberate, documented choice to skip it (a "your call").
rules:
${ruleLines}

# Lighthouse category gates (the full audit). Each is on by default.
categories:
${categoryLines}
`;
}

async function fileExists(path: string): Promise<boolean> {
  try {
    await access(path, constants.F_OK);
    return true;
  } catch {
    return false;
  }
}

/**
 * Scaffold a project for the Revivify lifecycle.
 *
 * Writes `.revivify.yaml` into `dir`. Non-destructive by default: if a config
 * already exists it is left untouched (re-run with `--force` to regenerate).
 * Emits a plain-language summary to stderr and a compact machine-readable line
 * to stdout, mirroring the dual-audience split of `revivify check`.
 *
 * Returns 0 on success (including the "already initialized" no-op).
 */
export async function runInit(dir: string, options: InitOptions): Promise<number> {
  const targetDir = resolve(dir);
  const configPath = join(targetDir, CONFIG_FILENAME);
  const exists = await fileExists(configPath);

  if (exists && !options.force) {
    process.stderr.write(
      `\nRevivify is already initialized here.\n` +
        `  ${CONFIG_FILENAME} already exists — leaving it untouched.\n` +
        `  Re-run with --force to regenerate it from the defaults.\n\n`,
    );
    process.stdout.write(`revivify init: skipped (${CONFIG_FILENAME} exists)\n`);
    return 0;
  }

  await writeFile(configPath, renderConfig(), "utf8");

  const verb = exists ? "Regenerated" : "Created";
  process.stderr.write(
    `\nRevivify is set up in ${targetDir}\n` +
      `  ${verb} ${CONFIG_FILENAME} — ship-ready bar ${DEFAULT_THRESHOLD}/10, every check on.\n` +
      `  Edit it to tune the bar or turn a check off (a deliberate "your call").\n` +
      `  Next: run \`revivify check\` to see where the page stands.\n\n`,
  );
  process.stdout.write(`revivify init: ${verb.toLowerCase()} ${CONFIG_FILENAME}\n`);
  return 0;
}
